[versions]
appdirs = "2.0.0"
caUhnHapiFhir = "8.12.0"
colormap = "0.9.511"
flatlaf = "3.7.2"
composeMultiplatform = "1.12.0"
composeMaterial3 = "1.12.0-SNAPSHOT+v-mazunin-enable-lifecycle-and-nav3-for-1-12-0-alpha02"
fuzzywuzzy = "1.4.0"
javaxXmlBind = "2.4.0-b180830.0359"
jgrapht = "1.5.3"
jungraphT = "1.4"
kotlin = "2.4.10"
kotlinxCoroutines = "1.11.0"
ktor = "3.5.2"
nativeJFileChooser = "1.6.4"
orgApacheCommons = "3.20.0"
orgApacheJena = "6.2.0"
orgApacheLoggingLog4j = "2.26.1"
orgApacheLoggingLog4jApiKotlin = "1.5.0"
orgSlf4j = "2.0.18"
rsyntaxtextarea = "3.6.3"

[libraries]
ca-gosyer-kotlin-multiplatform-appdirs = { module = "ca.gosyer:kotlin-multiplatform-appdirs", version.ref = "appdirs" }
ca-uhn-hapi-fhir-base = { module = "ca.uhn.hapi.fhir:hapi-fhir-base", version.ref = "caUhnHapiFhir" }
ca-uhn-hapi-fhir-structures-r4 = { module = "ca.uhn.hapi.fhir:hapi-fhir-structures-r4", version.ref = "caUhnHapiFhir" }
ca-uhn-hapi-fhir-validation = { module = "ca.uhn.hapi.fhir:hapi-fhir-validation", version.ref = "caUhnHapiFhir" }
com-fifesoft-rsyntaxtextarea = { module = "com.fifesoft:rsyntaxtextarea", version.ref = "rsyntaxtextarea" }
com-formdev-flatlaf = { module = "com.formdev:flatlaf", version.ref = "flatlaf" }
com-github-tomnelson-jungrapht-layout = { module = "com.github.tomnelson:jungrapht-layout", version.ref = "jungraphT" }
com-github-tomnelson-jungrapht-visualization = { module = "com.github.tomnelson:jungrapht-visualization", version.ref = "jungraphT" }
io-ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
io-ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
javax-xml-bind-jaxb-api = { module = "javax.xml.bind:jaxb-api", version.ref = "javaxXmlBind" }
li-flor-native-j-file-chooser = { module = "li.flor:native-j-file-chooser", version.ref = "nativeJFileChooser" }
me-xdrop-fuzzywuzzy = { module = "me.xdrop:fuzzywuzzy", version.ref = "fuzzywuzzy" }
net-mahdilamb-colormap = { module = "net.mahdilamb:colormap", version.ref = "colormap" }
org-apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "orgApacheCommons" }
org-apache-jena-arq = { module = "org.apache.jena:jena-arq", version.ref = "orgApacheJena" }
org-apache-jena-core = { module = "org.apache.jena:jena-core", version.ref = "orgApacheJena" }
org-apache-logging-log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "orgApacheLoggingLog4j" }
org-apache-logging-log4j-api-kotlin = { module = "org.apache.logging.log4j:log4j-api-kotlin", version.ref = "orgApacheLoggingLog4jApiKotlin" }
org-apache-logging-log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "orgApacheLoggingLog4j" }
org-apache-logging-log4j-layout-template-json = { module = "org.apache.logging.log4j:log4j-layout-template-json", version.ref = "orgApacheLoggingLog4j" }
org-apache-logging-log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "orgApacheLoggingLog4j" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMaterial3" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources-desktop", version.ref = "composeMultiplatform" }
compose-components-splitpane = { module = "org.jetbrains.compose.components:components-splitpane-desktop", version.ref = "composeMultiplatform"}

compose-uiToolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
org-jetbrains-kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
org-jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
org-jgrapht-core = { module = "org.jgrapht:jgrapht-core", version.ref = "jgrapht" }
org-jgrapht-ext = { module = "org.jgrapht:jgrapht-ext", version.ref = "jgrapht" }
org-slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "orgSlf4j" }

[plugins]
javafxplugin = { id = "org.openjfx.javafxplugin", version = "0.1.0" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
